version: 2.0
subscriptionId: 2ce9a29e-219e-422b-b9f8-5c5e54d5439e
resourceGroup: appgwlinux
registry: appgwreg
onboardingNotification: agic
dependencyNotification: agic

ownership:
  securityGroups:
  - groupName: northamerica\RCG-BRKT-22822
    permissions:
    - read
    - write

repos:

  - name: public/azure-application-gateway/kubernetes-ingress
    displayName: Azure Application Gateway Kubernetes Ingress
    description: No Description
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com
    syndications:
      - type: cloud
        destinations:
          - usnat
          - ussec
        tags:
          - source: /^v?\d\.\d{1,2}\.\d{1,2}$/
          - source: 1.3.0
          - source: 1.2.2
          - source: 1.2.1
          - source: 1.2.0
          - source: 1.2.0-rc3
  - name: public/azure-application-gateway/kubernetes-ingress-staging
    displayName: Azure Application Gateway Kubernetes Ingress Staging
    description: No Description
    logoUrl: https://mcrflowprodcentralus.blob.core.windows.net/defaultlogo/Microsoft_logo.svg?sp=r&st=2019-01-19T00:10:26Z&se=2033-11-04T07:10:26Z&spr=https&sv=2018-03-28&sig=dRn%2BJsqcKwsVdAMcdkzPAbydqSC%2BzBS9BwJUI9AflR4%3D&sr=b
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com
