version: 2.0
subscriptionId: b9d9436a-0c07-4fe8-b779-2c1030bd7997
resourceGroup: mcr-registry
registry: csemcr
onboardingNotification: azure-k8s-metrics-adapter
dependencyNotification: azure-k8s-metrics-adapter


repos:

  - name: public/k8s/metrics/adapter
    displayName: K8s Metrics Adapter
    readme: README.azure-k8s-metric-adapter.md
    description: An implementation of the Kubernetes Custom Metrics API and External Metrics API for Azure Services.
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://microsoft.com
    documentationLink: https://microsoft.com


