version: 2.0
subscriptionId: 8c0e0d10-c2d6-42b8-b1d9-e7132b6f18a3
resourceGroup: openapi-platform-preview
registry: azopenapi
onboardingNotification: openapimcronboarding
dependencyNotification: openapimcrdependency

repos:

  - name: internal/openapi/validate-v2
    displayName: OpenAPI Validation Service v2
    readme: README.validate-v2.md
    description: OpenAPI Validation Service v2
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://aka.ms/openapihub
    documentationLink: https://aka.ms/openapihub
