version: 2.0
subscriptionId: 5ed2dcb6-29bb-40de-a855-8c24a8260343
resourceGroup: edge-virtual-kubelet-do-not-delete
registry: EdgeVK
onboardingNotification: edgedevs
dependencyNotification: edgedevs

repos:

  - name: public/iotedge/vk-provider
    displayName: IoT Edge Virutal Kubelet Provider
    readme: README.md
    description: This image contains the implementation of a Virutal Kubelet provider for Azure IoT Edge
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://github.com/Azure/iot-edge-virtual-kubelet-provider
    documentationLink: https://github.com/Azure/iot-edge-virtual-kubelet-provider
    syndications:
      - type: dockerhub
        repository: microsoft/iot-edge-vk-provider
        contentUpdate: true
        imageUpdate: true
        tags:
          - source: latest
            target: latest