version: 2.0
subscriptionId: 2ae36068-ae27-46b1-be02-60f387f32f81
resourceGroup: destinationsecurity
registry: destinationsecurity
onboardingNotification: destinationsecurity
dependencyNotification: destinationsecurity

repos:
  - name: public/samples/basic-linux-app
    displayName: Basic Linux Application
    readme: README.basic-linux-app.md
    description: Basic sample application that shows security best practices for new Azure developers
    logoUrl: https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://docs.microsoft.com/en-us/azure/security/develop/
    documentationLink: https://docs.microsoft.com/en-us/azure/security/develop/
    syndications:
      - type: dockerhub
        repository: microsoft/basic-linux-app
        imageUpdate: false
