version: 2.0
subscriptionId: 8b3b8a60-1dd0-4824-8770-2ed6a55d8e27
resourceGroup: synapsemcr
registry: synapsemcr
onboardingNotification: synapsemdnot
dependencyNotification: synapsemdnot

repos:
  - name: public/azuresynapse/synapse-prometheus-connector
    displayName: Synapse - Azure Synapse Spark Pools Prometheus Connector
    readme: README.synapse-prometheus-connector.md
    description: Azure Synapse Spark Pools Prometheus Connector Container image
    logoUrl:  https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://docs.microsoft.com/en-us/azure/synapse-analytics/overview-what-is
    documentationLink: https://docs.microsoft.com/en-us/azure/synapse-analytics/overview-what-is
  
  - name: internal/azuresynapse/synapse-prometheus-connector
    displayName: Synapse - Azure Synapse Spark Pools Prometheus Connector
    readme: README.synapse-prometheus-connector.md
    description: Azure Synapse Spark Pools Prometheus Connector Container image
    logoUrl:  https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg
    supportLink: https://docs.microsoft.com/en-us/azure/synapse-analytics/overview-what-is
    documentationLink: https://docs.microsoft.com/en-us/azure/synapse-analytics/overview-what-is